### PR TITLE
Update jenkins-plugin-runtime and jruby-openssl to fix #26

### LINKED ISSUE #26: FATAL: java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1InputStream.readObject()
Hi,

I've been trying to configure the vagrant plugin but I keep running into some openssl issue:

https://gist.github.com/e614e987f111d5e82650

My Vagrant file:

https://gist.github.com/fd4843af9097cc48179d

I'm running:
- Jenkins ver. 1.491
- 0.10 of the ruby runtime plugin
- 0.1.4 of the vagrant plugin

I'm a bit stuck at this point. Any help is appreciated.

### PR DESCRIPTION
**Pull request by tpodom**
In order to fix #26 the Jenkins team must first accept the pull requests https://github.com/jenkinsci/jenkins.rb/pull/70 and https://github.com/stapler/stapler/pull/14.

I'm not sure if there's a cleaner way to handle this but after upgrading to jenkins-plugin-runtime 0.2.3 with vagrant-plugin I had to hand edit my config.xmls because they were referencing Jenkins::Plugin::Proxies::Builder instead of Jenkins::Tasks::BuilderProxy.

For users that are interested, I have built a custom version of the ruby-runtime plugin for Jenkins.  You can download [ruby-runtime.hpi](https://dl.dropbox.com/u/35989164/ruby-runtime.hpi) and [vagrant-plugin.hpi](https://dl.dropbox.com/u/35989164/vagrant.hpi) and install both of those plugins into Jenkins 1.505+.

### CODE REVIEW

**Comment by riuvshin** [comment]
Hi guys!  jenkinsci/jenkins.rb#70 and stapler/stapler#14 is closed! what's next?

**Comment by turboladen** [comment]
+1

**Comment by jhansche** [comment]
@rtyler Any progress on this?  We'd like to be able to use this plugin, but the list of known issues in the wiki page are **huge** blockers for us.  Requiring the Jenkins version to be pinned to 1.487 is not a viable solution for this.

**Comment by wenns** [comment]
+1

**Comment by exoinvitemain** [comment]
@rtyler Please check it out as soon as u can, thanks!

**Comment by riuvshin** [comment]
@rtyler Hello, any progress on this? It's a very critical for lot of users...

**Pull request merged**
